version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - '5432:5432/tcp'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
    driver: local
